package com.am.project.utils

const val LOG_TAG_NAME = "NASA_APOD_PROJECT_TAG"
const val NETWORK_FAIL = "NO_INTERNET_FOUND"
const val NO_DATA_FOUND = "NO_DATA_FOUND"
const val GENERAL_ERROR = "FETCH_FAILED"
const val SUCCESS = "SUCCESS"
const val CODE_400 = "CODE_400"
const val DB_UPDATE_FAILED_ERROR = "DB_UPDATE_FAILED_ERROR"
const val MEDIA_TYPE_VIDEO = "video"
const val PREFS_UID = "COM_AM_UTILS_UTIL_CONST"
const val PREF_HOME_APOD_ID_KEY = "PREF_HOME_APOD_ID_KEY"


